//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGSApps.Net.Security.ServiceP3UserManagement {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceP3UserManagement.wsOuthSoap")]
    public interface wsOuthSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConnTes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.ConnectionInfo ConnTes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getErrorMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.ErrorInfo getErrorMessage(string xUsername, string xKode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cekValidasiPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo cekValidasiPassword(string xUsername, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/encript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string encript(string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/decript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string decript(string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/openBlokirAkun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo openBlokirAkun(string xUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/blokirAkun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo blokirAkun(string xUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FormChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo FormChangePassword(string xUsername, string xOldPassword, string xNewPassword, string xConfirmPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MigrasiPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo MigrasiPassword(string xUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/valLoginAkun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.UserAkunInfo valLoginAkun(string xIDAPLIKASI, string xUsername, string xPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateActLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void updateActLog(string xIDAPLIKASI, string xUSERNAME, string xActivity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/encriptALLPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string encriptALLPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kirimSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string kirimSMS(string xUser, string xpassword, string xNoHP, string xText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kirimEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string kirimEmail(string xUser, string xpassword, string xEmailPenerima, string xJudul, string xBody);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kirimEmailwithAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string kirimEmailwithAttachment(string xUser, string xpassword, string xEmailPenerima, string xJudul, string xBody, object xAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPasswordKirimEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResetPasswordKirimEmail(string xUser, string xpasswordBaru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaftarPegawai", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] DaftarPegawai(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verifySESSION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.UserAkunInfo verifySESSION(string keysid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DaftarUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] DaftarUser(string prefixText, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/valInfoAksesAkun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable valInfoAksesAkun(string xIDAplikasi, string xusername, string xpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/xGetValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BGSApps.Net.Security.ServiceP3UserManagement.ws_addResponse xGetValues(string param1, string param2);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ConnectionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responTypeField;
        
        private string responTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responType {
            get {
                return this.responTypeField;
            }
            set {
                this.responTypeField = value;
                this.RaisePropertyChanged("responType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responText {
            get {
                return this.responTextField;
            }
            set {
                this.responTextField = value;
                this.RaisePropertyChanged("responText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ws_addResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable param3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataTable param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserAkunInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responTypeField;
        
        private string responTextField;
        
        private string iDUSERField;
        
        private string uSERNAMEField;
        
        private string nAMAField;
        
        private string kELASField;
        
        private string nAMA_JABATANField;
        
        private string sANDIField;
        
        private string kD_CABANGField;
        
        private string nAMA_CABANGField;
        
        private string kD_DITField;
        
        private string nAMA_DITField;
        
        private string kD_SUBField;
        
        private string nAMA_SUBField;
        
        private string kD_SEKField;
        
        private string nAMA_SEKField;
        
        private string hAKAKSESField;
        
        private string hAKAKSES_DESCField;
        
        private string pARENT_HAKAKSESField;
        
        private string pARENT_HAKAKSES_DESCField;
        
        private string eMAILField;
        
        private string hpField;
        
        private string sTATUSField;
        
        private string uRLField;
        
        private string uRL_CPField;
        
        private string nORUTField;
        
        private string dGTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responType {
            get {
                return this.responTypeField;
            }
            set {
                this.responTypeField = value;
                this.RaisePropertyChanged("responType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responText {
            get {
                return this.responTextField;
            }
            set {
                this.responTextField = value;
                this.RaisePropertyChanged("responText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IDUSER {
            get {
                return this.iDUSERField;
            }
            set {
                this.iDUSERField = value;
                this.RaisePropertyChanged("IDUSER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string USERNAME {
            get {
                return this.uSERNAMEField;
            }
            set {
                this.uSERNAMEField = value;
                this.RaisePropertyChanged("USERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NAMA {
            get {
                return this.nAMAField;
            }
            set {
                this.nAMAField = value;
                this.RaisePropertyChanged("NAMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string KELAS {
            get {
                return this.kELASField;
            }
            set {
                this.kELASField = value;
                this.RaisePropertyChanged("KELAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NAMA_JABATAN {
            get {
                return this.nAMA_JABATANField;
            }
            set {
                this.nAMA_JABATANField = value;
                this.RaisePropertyChanged("NAMA_JABATAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SANDI {
            get {
                return this.sANDIField;
            }
            set {
                this.sANDIField = value;
                this.RaisePropertyChanged("SANDI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KD_CABANG {
            get {
                return this.kD_CABANGField;
            }
            set {
                this.kD_CABANGField = value;
                this.RaisePropertyChanged("KD_CABANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string NAMA_CABANG {
            get {
                return this.nAMA_CABANGField;
            }
            set {
                this.nAMA_CABANGField = value;
                this.RaisePropertyChanged("NAMA_CABANG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string KD_DIT {
            get {
                return this.kD_DITField;
            }
            set {
                this.kD_DITField = value;
                this.RaisePropertyChanged("KD_DIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NAMA_DIT {
            get {
                return this.nAMA_DITField;
            }
            set {
                this.nAMA_DITField = value;
                this.RaisePropertyChanged("NAMA_DIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string KD_SUB {
            get {
                return this.kD_SUBField;
            }
            set {
                this.kD_SUBField = value;
                this.RaisePropertyChanged("KD_SUB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NAMA_SUB {
            get {
                return this.nAMA_SUBField;
            }
            set {
                this.nAMA_SUBField = value;
                this.RaisePropertyChanged("NAMA_SUB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string KD_SEK {
            get {
                return this.kD_SEKField;
            }
            set {
                this.kD_SEKField = value;
                this.RaisePropertyChanged("KD_SEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NAMA_SEK {
            get {
                return this.nAMA_SEKField;
            }
            set {
                this.nAMA_SEKField = value;
                this.RaisePropertyChanged("NAMA_SEK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string HAKAKSES {
            get {
                return this.hAKAKSESField;
            }
            set {
                this.hAKAKSESField = value;
                this.RaisePropertyChanged("HAKAKSES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string HAKAKSES_DESC {
            get {
                return this.hAKAKSES_DESCField;
            }
            set {
                this.hAKAKSES_DESCField = value;
                this.RaisePropertyChanged("HAKAKSES_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string PARENT_HAKAKSES {
            get {
                return this.pARENT_HAKAKSESField;
            }
            set {
                this.pARENT_HAKAKSESField = value;
                this.RaisePropertyChanged("PARENT_HAKAKSES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string PARENT_HAKAKSES_DESC {
            get {
                return this.pARENT_HAKAKSES_DESCField;
            }
            set {
                this.pARENT_HAKAKSES_DESCField = value;
                this.RaisePropertyChanged("PARENT_HAKAKSES_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
                this.RaisePropertyChanged("EMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string HP {
            get {
                return this.hpField;
            }
            set {
                this.hpField = value;
                this.RaisePropertyChanged("HP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string URL_CP {
            get {
                return this.uRL_CPField;
            }
            set {
                this.uRL_CPField = value;
                this.RaisePropertyChanged("URL_CP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string NORUT {
            get {
                return this.nORUTField;
            }
            set {
                this.nORUTField = value;
                this.RaisePropertyChanged("NORUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DGT {
            get {
                return this.dGTField;
            }
            set {
                this.dGTField = value;
                this.RaisePropertyChanged("DGT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PasswordInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responTypeField;
        
        private string responTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responType {
            get {
                return this.responTypeField;
            }
            set {
                this.responTypeField = value;
                this.RaisePropertyChanged("responType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responText {
            get {
                return this.responTextField;
            }
            set {
                this.responTextField = value;
                this.RaisePropertyChanged("responText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kodeField;
        
        private string keteranganField;
        
        private string responTypeField;
        
        private string responTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
                this.RaisePropertyChanged("kode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string keterangan {
            get {
                return this.keteranganField;
            }
            set {
                this.keteranganField = value;
                this.RaisePropertyChanged("keterangan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string responType {
            get {
                return this.responTypeField;
            }
            set {
                this.responTypeField = value;
                this.RaisePropertyChanged("responType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string responText {
            get {
                return this.responTextField;
            }
            set {
                this.responTextField = value;
                this.RaisePropertyChanged("responText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsOuthSoapChannel : BGSApps.Net.Security.ServiceP3UserManagement.wsOuthSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsOuthSoapClient : System.ServiceModel.ClientBase<BGSApps.Net.Security.ServiceP3UserManagement.wsOuthSoap>, BGSApps.Net.Security.ServiceP3UserManagement.wsOuthSoap {
        
        public wsOuthSoapClient() {
        }
        
        public wsOuthSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsOuthSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsOuthSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsOuthSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.ConnectionInfo ConnTes() {
            return base.Channel.ConnTes();
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.ErrorInfo getErrorMessage(string xUsername, string xKode) {
            return base.Channel.getErrorMessage(xUsername, xKode);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo cekValidasiPassword(string xUsername, string xPassword) {
            return base.Channel.cekValidasiPassword(xUsername, xPassword);
        }
        
        public string encript(string xPassword) {
            return base.Channel.encript(xPassword);
        }
        
        public string decript(string xPassword) {
            return base.Channel.decript(xPassword);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo openBlokirAkun(string xUsername) {
            return base.Channel.openBlokirAkun(xUsername);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo blokirAkun(string xUsername) {
            return base.Channel.blokirAkun(xUsername);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo FormChangePassword(string xUsername, string xOldPassword, string xNewPassword, string xConfirmPassword) {
            return base.Channel.FormChangePassword(xUsername, xOldPassword, xNewPassword, xConfirmPassword);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.PasswordInfo MigrasiPassword(string xUsername) {
            return base.Channel.MigrasiPassword(xUsername);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.UserAkunInfo valLoginAkun(string xIDAPLIKASI, string xUsername, string xPassword) {
            return base.Channel.valLoginAkun(xIDAPLIKASI, xUsername, xPassword);
        }
        
        public void updateActLog(string xIDAPLIKASI, string xUSERNAME, string xActivity) {
            base.Channel.updateActLog(xIDAPLIKASI, xUSERNAME, xActivity);
        }
        
        public string encriptALLPassword() {
            return base.Channel.encriptALLPassword();
        }
        
        public string kirimSMS(string xUser, string xpassword, string xNoHP, string xText) {
            return base.Channel.kirimSMS(xUser, xpassword, xNoHP, xText);
        }
        
        public string kirimEmail(string xUser, string xpassword, string xEmailPenerima, string xJudul, string xBody) {
            return base.Channel.kirimEmail(xUser, xpassword, xEmailPenerima, xJudul, xBody);
        }
        
        public string kirimEmailwithAttachment(string xUser, string xpassword, string xEmailPenerima, string xJudul, string xBody, object xAttachment) {
            return base.Channel.kirimEmailwithAttachment(xUser, xpassword, xEmailPenerima, xJudul, xBody, xAttachment);
        }
        
        public string ResetPasswordKirimEmail(string xUser, string xpasswordBaru) {
            return base.Channel.ResetPasswordKirimEmail(xUser, xpasswordBaru);
        }
        
        public string[] DaftarPegawai(string prefixText, int count) {
            return base.Channel.DaftarPegawai(prefixText, count);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.UserAkunInfo verifySESSION(string keysid) {
            return base.Channel.verifySESSION(keysid);
        }
        
        public string[] DaftarUser(string prefixText, int count) {
            return base.Channel.DaftarUser(prefixText, count);
        }
        
        public System.Data.DataTable valInfoAksesAkun(string xIDAplikasi, string xusername, string xpassword) {
            return base.Channel.valInfoAksesAkun(xIDAplikasi, xusername, xpassword);
        }
        
        public BGSApps.Net.Security.ServiceP3UserManagement.ws_addResponse xGetValues(string param1, string param2) {
            return base.Channel.xGetValues(param1, param2);
        }
    }
}
